### ISSUE TITLE
General notes

### ISSUE THREAD

**Issue by hshahwan** [FACG6/leannky-Anty#12]
Hi Team,

@AymanAlqoqa @denaHS @alaabadra @naremanhilles 

### I have important notes to start work in a perfect way.
- Firstly, use labels In progress, waiting for review.
- assign yourself to the PR.
- ask your teammates  to review your  PR, If they approved it, so you can request my review
- Don't add not related files to the PR.
- Use beautify extension for CSS files to avoid indentation.
- Make sure your linter is working.
-Make sure your Travis is working.
-Care about git-flow. (make sure after finished from branch return to master branch to start to work on another issue).
- make sure you pull master before you push your work.
- checkout your branch when you start work on a new issue.
- don't be too late when I request changes.
- don't push any code not working.
- put the time for your task by using the label, how much time that you need to do like this 'T 2d'.
- When you open PR describe what you did.
- Write a meaningful name. 
  - the name of the variable or classes should answer all the big questions.
  - it should tell you why it exists, what it does, and how it is used.
  - className: classes and objects should have been a noun or noun phrases like a dashboard.
  - methods Name: methods should have been a verb or verb phrases like editProfile.
- When you write function should care about.
  - should be small
  - A function shouldn't have more than 3 arguments.
  - When function seems to need more than two or three arguments, it is likely that some of those arguments ought to wrapped into a class of their own.
  - Reducing the number of arguments by creating objects out of them may seem like cheating but it's not.
- Delete the branch after  the merge

**Comment by ahmedalmi95** [comment]
A function shouldn't have more than 3 arguments. else Error-handling middleware I think takes 4 arguments.

I wanna to benefit from your advices.
thank you @hshahwan this is a great advices.

**Comment by AymanAlqoqa** [comment]
thank you, i agree with ahmed regarding his point about maximum number of arguments, server error needs 4 arguments (error, request, response, next), maybe it is assumed special case.
thanks for your great advice
